### ISSUE TITLE
error on bulletin

### ISSUE THREAD

**Issue by lostfile** [andrewwyatt/photonbbs#5]
wen i try to run the command to edit a bulletin it gives me this error
 ERROR: Could not load theme file [/opt/photonbbs/data/themes/mbbs] , exiting..
Exiting..
im currently ruining the BBS server on a raspberry pi and i would also would like to know how i can use  qemu or dosbox to at lest run a single node door game because dosemu isn't and option for me well i could try finding some text games that run on linux like dopewars

**Comment by lostfile1** [comment]
Also I notice there's a couple of inconsistency is with the  instructions in the readme file  It's saying to create a user named chat when  It actually requires to create a user named bbs

**Comment by andrewwyatt** [comment]
Thanks for pointing these out, I'll get them cleaned up as soon as possible.  As a workaround to the bulletin problem you should be able to change line 72 of bulledit.pl from "mbbs" to "photon".

You'll have to research running quemu or dosbox on the arm platform, I don't have any experience with it.  The emulator would have to support redirecting output over COM1 though, like a modem on a real system.

**Comment by lostfile** [comment]
i wonder if this could help
http://cyberiabbs.zapto.org/dispfile.php?textfile=gfiles/mystic/dosdoors-howto.txt&title=How+To+Add+DOS+doors+to+Raspberry+Pi+Mystic

**Comment by andrewwyatt** [comment]
Looks like it, let me know how it works out for you.

**Comment by lostfile** [comment]
im trying to use dosbox but im having problems with SDL

**Comment by andrewwyatt** [comment]
Pull the latest bulledit.pl from master and see if that corrects your bulletins issue.

**Comment by andrewwyatt** [comment]
Issues appear to be corrected in my testing.
