### ISSUE TITLE
User created  Bulletins

### ISSUE THREAD

**Issue by lostfile1** [andrewwyatt/photonbbs#6]
I have a feature request to make a email system or user created bulletins or some way to msg you friends offline

**Comment by lostfile** [comment]
or maybe a fourm or message areas like mystic

**Comment by andrewwyatt** [comment]
This project isn't really active anymore, it's just something that I use for container deployment testing. 
 I'd have to rely on the community to provide new features.

**Comment by lostfile** [comment]
well i am working on some thing that could work with it
https://github.com/lostfile/messagesh/blob/master/board.sh
